---
- name: Ensure nginx deployed
  hosts: webservers
  remote_user: runner
  become: yes
  become_method: sudo

  tasks:
  - name: Ensure nginx installed
    ansible.builtin.apt:
      name: nginx
      state: latest
      update_cache: true
  - name: Ensure index exists with content
    ansible.builtin.copy:
       src: ./index.html
       dest: /var/www/html/index.nginx-debian.html
       owner: root
       group: root
       mode: '0666'
